-- 纯领域合同回滚断言；不创建账号、课程、课堂或草稿，不修改旧快照。
begin;
do $$
declare
  base jsonb:='{"sceneId":"47-create","params":{"nextNode":2,"nextEdge":1,"nextRecord":1,"nextStroke":1,"activeNode":-1,"activeEdge":-1,"currentStroke":-1,"figureMode":0,"rays":5,"columns":3,"rows":2,"levels":3,"a.0":0,"b.0":1},"points":{"node.0":{"x":280,"y":360},"node.1":{"x":600,"y":360}},"flags":{"grid":false,"measures":false,"names":false,"degrees":false,"intersections":true,"edit":false,"snap":false,"repeat":false,"highlights":true},"marks":[],"phase":1}';
  sample jsonb; valid_cross jsonb; empty_ jsonb; wrapped jsonb; i integer;
begin
  if not public.tool_plane_network_state_is_valid(base) then raise exception 'network: default segment rejected'; end if;
  sample:=jsonb_set(base,'{sceneId}','"52-create"');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: path default rejected'; end if;
  empty_:=jsonb_set(jsonb_set(base,'{points}','{}'),'{params}',(base->'params')-'a.0'-'b.0');
  if not public.tool_plane_network_state_is_valid(empty_) then raise exception 'network: empty reusable stage rejected'; end if;
  sample:=jsonb_set(base,'{params}',(base->'params')||'{"a.1":0,"b.1":1,"nextEdge":2}');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: duplicate edge accepted'; end if;
  sample:=jsonb_set(base,'{params,b.0}','0');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: self edge accepted'; end if;
  sample:=jsonb_set(base,'{params,b.0}','80');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: dangling endpoint accepted'; end if;
  sample:=jsonb_set(base,'{params,nextNode}','1');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: stale id counter accepted'; end if;
  sample:=jsonb_set(base,'{params}',(base->'params')-'nextRecord');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: missing required key accepted'; end if;
  sample:=jsonb_set(base,'{params}',(base->'params')||'{"unexpected":1}');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: unknown key accepted'; end if;
  sample:=jsonb_set(base,'{points}',(base->'points')||'{"node.00":{"x":1,"y":1}}');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: noncanonical id accepted'; end if;
  sample:=jsonb_set(jsonb_set(base,'{points}',(base->'points')||'{"node.2":{"x":440,"y":360}}'),'{params,nextNode}','3');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: unsplit interior node accepted'; end if;
  sample:=jsonb_set(jsonb_set(base,'{points}',(base->'points')||'{"node.2":{"x":440,"y":200},"node.3":{"x":440,"y":500}}'),'{params}',(base->'params')||'{"nextNode":4,"nextEdge":2,"a.1":2,"b.1":3}');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: unrepresented crossing accepted'; end if;
  valid_cross:=jsonb_set(jsonb_set(base,'{points}',(base->'points')||'{"node.2":{"x":440,"y":200},"node.3":{"x":440,"y":500},"node.4":{"x":440,"y":360}}'),'{params}',(base->'params')||'{"nextNode":5,"nextEdge":4,"a.0":0,"b.0":4,"a.1":1,"b.1":4,"a.2":2,"b.2":4,"a.3":3,"b.3":4}');
  if not public.tool_plane_network_state_is_valid(valid_cross) then raise exception 'network: represented crossing rejected'; end if;
  sample:=jsonb_set(jsonb_set(valid_cross,'{marks}','["segment.1.0.0","segment.1.1.1"]'),'{params,nextRecord}','2');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: continuously covered segment rejected'; end if;
  sample:=jsonb_set(sample,'{params}',(sample->'params')-'a.1'-'b.1');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: record crossing a gap accepted'; end if;
  sample:=jsonb_set(base,'{marks}','["pick.1.0"]');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: pick index gap accepted'; end if;
  sample:=jsonb_set(base,'{marks}','["pick.0.0","pick.1.0"]');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: repeated pick accepted'; end if;
  sample:=jsonb_set(jsonb_set(base,'{points}',(base->'points')||'{"node.2":{"x":440,"y":360},"node.3":{"x":280,"y":160}}'),'{params}',(base->'params')||'{"nextNode":4,"nextEdge":3,"nextRecord":2,"figureMode":1,"a.0":0,"b.0":2,"a.1":1,"b.1":2,"a.2":0,"b.2":3}');
  sample:=jsonb_set(sample,'{marks}','["angle.1.0.3","angle.1.1.0","angle.1.2.2"]');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: valid nonzero angle rejected'; end if;
  sample:=jsonb_set(jsonb_set(sample,'{params,nextRecord}','3'),'{marks}',(sample->'marks')||'["angle.2.0.1","angle.2.1.0","angle.2.2.3"]');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: same directed rays with far endpoint counted twice'; end if;
  sample:=jsonb_set(sample,'{marks}','["angle.1.0.1","angle.1.1.0","angle.1.2.2"]');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: overlapping zero-degree arms accepted'; end if;
  sample:=jsonb_set(sample,'{marks}','["angle.1.0.0","angle.1.1.2","angle.1.2.1"]');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: straight angle rejected'; end if;
  sample:=jsonb_set(jsonb_set(jsonb_set(valid_cross,'{sceneId}','"52-create"'),'{params}',(valid_cross->'params')||'{"currentStroke":1,"nextStroke":2}'),'{marks}','["stroke.1.0.0","stroke.1.1.4","stroke.1.2.1"]');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: straight trace through split node rejected'; end if;
  sample:=jsonb_set(sample,'{marks}','["stroke.1.0.0","stroke.1.1.1"]');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: unexpanded shortcut trace accepted'; end if;
  sample:=jsonb_set(jsonb_set(jsonb_set(base,'{sceneId}','"52-create"'),'{params}',(base->'params')||'{"currentStroke":1,"nextStroke":2}'),'{marks}','["stroke.1.0.0","stroke.1.1.1"]');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: valid trace rejected'; end if;
  sample:=jsonb_set(sample,'{marks}','["stroke.1.0.0","stroke.1.1.1","stroke.1.2.0"]');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: repeated edge accepted without permission'; end if;
  sample:=jsonb_set(sample,'{flags,repeat}','true');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: permitted repeated edge rejected'; end if;
  sample:=jsonb_set(jsonb_set(base,'{sceneId}','"52-create"'),'{params,currentStroke}','1');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: stale current stroke accepted'; end if;
  -- 预算边界：96 个独立节点可存，第 97 个节点明确拒绝。
  sample:=empty_;
  for i in 0..95 loop sample:=jsonb_set(sample,'{points}',(sample->'points')||jsonb_build_object('node.'||i,jsonb_build_object('x',i*10,'y',50))); end loop;
  sample:=jsonb_set(sample,'{params,nextNode}','96');
  if not public.tool_plane_network_state_is_valid(sample) then raise exception 'network: 96-node boundary rejected'; end if;
  sample:=jsonb_set(jsonb_set(sample,'{points}',(sample->'points')||'{"node.96":{"x":960,"y":50}}'),'{params,nextNode}','97');
  if public.tool_plane_network_state_is_valid(sample) then raise exception 'network: 97 nodes accepted'; end if;
  wrapped:=jsonb_build_object('toolId','plane-patterns','contentVersion','plane-patterns-lesson-v2','payload',jsonb_build_object('title','可编辑图网络','initial',base));
  if not public.tool_plane_network_scene_is_valid(wrapped) then raise exception 'network: scene envelope rejected'; end if;
  if public.tool_plane_network_scene_is_valid(jsonb_set(wrapped,'{toolId}','"plane-graph-path"')) then raise exception 'network: wrong tool accepted'; end if;
  if public.tool_plane_network_scene_is_valid(jsonb_set(wrapped,'{contentVersion}','"plane-patterns-lesson-v1"')) then raise exception 'network: helper claims legacy version'; end if;
  if public.tool_plane_network_scene_is_valid(jsonb_set(wrapped,'{payload,title}','" "')) then raise exception 'network: blank title accepted'; end if;
  if public.tool_plane_network_scene_is_valid(jsonb_set(wrapped,'{payload,unexpected}','true')) then raise exception 'network: extra payload key accepted'; end if;
  raise notice 'plane network contract assertions passed';
end;
$$;
rollback;
