const zh = {
  title: "立体观察", tools: "立体工具", close: "收起", add: "添加立体", objects: "实体与尺寸", selected: "当前实体", remove: "移除当前实体", empty: "点击右侧加号，放入一个立体。", limit: "最多同时摆放 16 个立体", orbit: "旋转观察", pan: "平移视野", move: "移动实体", turn: "转动实体", color: "标色", transparent: "透明", opacity: "不透明度", face: "观察面", edge: "观察棱与边界", vertex: "观察顶点", noEdges: "这个实体没有棱或圆周边界。", noVertices: "这个实体没有顶点。", clearFeature: "取消突出显示", settings: "显示设置", grid: "X–Z 网格", axes: "坐标轴", reset: "恢复备课起点", fit: "适配视野", undo: "撤销", redo: "重做", step: "移动半格", moveHint: "拖动 X / Y / Z 轴箭头移动当前实体；空白处仍可旋转观察。", turnHint: "转动实体本身，观察面、棱与顶点的位置变化。", featureHint: "点击实体上的面，或在下面选择。曲面和圆周边界按实际结构显示。", syncError: "本次课堂操作未保存，已保留确认后的现场，请重试。", fallback: "当前设备未能启动 3D 画布，请启用 WebGL 后重试。", surface: "曲面", boundary: "圆周边界", colors: ["绿色", "红色", "黄色", "蓝色", "紫色", "米色"],
  axisSnap: "视角吸附", enableAxisSnap: "开启视角吸附", disableAxisSnap: "关闭视角吸附", moveSnap: "移动吸附", enableMoveSnap: "开启移动吸附", disableMoveSnap: "关闭移动吸附",
  kinds: { cube: "正方体", cuboid: "长方体", "triangular-prism": "三棱柱", "square-pyramid": "四棱锥", cylinder: "圆柱", cone: "圆锥", sphere: "球" },
  dimensions: { width: "宽", height: "高", depth: "深", radius: "半径" },
  views: { angle: "立体视角", front: "正面视角", left: "左侧视角", right: "右侧视角", top: "顶面视角", bottom: "底面视角" },
  faces: { front: "前面", back: "后面", left: "左面", right: "右面", top: "上面", bottom: "底面", surface: "曲面" },
};
type SolidMessages = { [K in keyof typeof zh]: typeof zh[K] extends string ? string : typeof zh[K] extends string[] ? string[] : { [J in keyof typeof zh[K]]: string } };
const en: SolidMessages = {
  title: "Solid geometry", tools: "Solid tools", close: "Close", add: "Add a solid", objects: "Solids & dimensions", selected: "Selected solid", remove: "Remove selected solid", empty: "Use the plus button on the right to add a solid.", limit: "Up to 16 solids", orbit: "Orbit", pan: "Pan view", move: "Move solid", turn: "Rotate solid", color: "Color", transparent: "Transparency", opacity: "Opacity", face: "Explore faces", edge: "Explore edges & rims", vertex: "Explore vertices", noEdges: "This solid has no edges or circular rims.", noVertices: "This solid has no vertices.", clearFeature: "Clear highlight", settings: "Display settings", grid: "X–Z grid", axes: "Axes", reset: "Restore prepared start", fit: "Fit view", undo: "Undo", redo: "Redo", step: "Move half a unit", moveHint: "Drag the X / Y / Z arrows to move the selected solid. Drag empty space to orbit.", turnHint: "Rotate the solid itself and observe how its faces, edges and vertices move.", featureHint: "Click a face on the solid or select it below. Curved surfaces and circular rims reflect the actual solid.", syncError: "The classroom change was not saved. The confirmed scene is retained; please retry.", fallback: "The 3D canvas could not start. Enable WebGL and try again.", surface: "Curved surface", boundary: "Circular rim", colors: ["Green", "Red", "Yellow", "Blue", "Purple", "Sand"],
  axisSnap: "View snapping", enableAxisSnap: "Enable view snapping", disableAxisSnap: "Disable view snapping", moveSnap: "Movement snapping", enableMoveSnap: "Enable movement snapping", disableMoveSnap: "Disable movement snapping",
  kinds: { cube: "Cube", cuboid: "Cuboid", "triangular-prism": "Triangular prism", "square-pyramid": "Square pyramid", cylinder: "Cylinder", cone: "Cone", sphere: "Sphere" },
  dimensions: { width: "Width", height: "Height", depth: "Depth", radius: "Radius" },
  views: { angle: "3D view", front: "Front view", left: "Left view", right: "Right view", top: "Top view", bottom: "Bottom view" },
  faces: { front: "Front", back: "Back", left: "Left", right: "Right", top: "Top", bottom: "Bottom", surface: "Curved surface" },
};
export function solidGeometryMessages(locale: string): SolidMessages { return locale === "en" ? en : zh; }
