// @vitest-environment jsdom
import { act,createElement,type ComponentProps,type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { NextIntlClientProvider } from 'next-intl';
import { afterEach,expect,it,vi } from 'vitest';
import messages from '../messages/zh.json';
import { EnrollmentPlacementWorkbench } from '@/features/school/EnrollmentPlacementWorkbench';
import type { EnrollmentPlacementBoard } from '@/features/school/enrollment-workflow-contract';
const calls=vi.hoisted(()=>({move:vi.fn(),change:vi.fn(),preview:vi.fn()}));
vi.mock('@/features/school/enrollment-workflow-actions',()=>({moveEnrollmentSeatAction:calls.move}));
vi.mock('@/features/school/enrollment-placement-change-actions',()=>({changeEnrollmentPlacementAction:calls.change,previewEnrollmentSessionTransferAction:calls.preview}));
vi.mock('@/features/school/SchoolSupportInlineEntry',()=>({SchoolSupportSeatEntry:()=>null}));
vi.mock('@/features/school/SchoolSupportPendingRows',()=>({SchoolSupportPendingRows:()=>null}));
vi.mock('@/features/school/Student360Sheet',()=>({Student360Trigger:({children,className}:{children:ReactNode;className?:string})=>createElement('button',{type:'button',className},children)}));
vi.mock('@/i18n/navigation',()=>({Link:({children,...props}:ComponentProps<'a'>)=>createElement('a',props,children),useRouter:()=>({refresh:vi.fn()}),usePathname:()=>'/dashboard/followups/enrollments'}));
const id=(n:number)=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const board:EnrollmentPlacementBoard={options:{courses:[{id:id(1),title:'数学',productCode:null,grade:3,classType:'G+'}],terms:[{id:id(2),name:'秋季',isCurrent:true,startsOn:null,endsOn:null}],classrooms:[3,4].map(n=>({id:id(n),name:n===3?'原班':'目标班',courseId:id(1),termId:id(2),capacity:3,activeCount:n===3?1:0,teacherNames:'教师',sessions:[],operationalStatus:'active'}))},enrollments:[],members:[{membershipId:id(5),studentId:id(6),name:'小林',phone:'',classroomId:id(3),enrollmentId:null,note:'',recommendation:'',seat:1,status:'active'}]};
let cleanup=async()=>{};
afterEach(async()=>{await cleanup();localStorage.clear();sessionStorage.clear();vi.unstubAllGlobals();});
it('opens the transfer choice after dragging across classes and leaves the roster unchanged until confirmation',async()=>{
  Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
  vi.stubGlobal('crypto',{getRandomValues:globalThis.crypto.getRandomValues.bind(globalThis.crypto)});
  HTMLElement.prototype.setPointerCapture=vi.fn();HTMLElement.prototype.releasePointerCapture=vi.fn();HTMLElement.prototype.hasPointerCapture=()=>true;
  HTMLElement.prototype.scrollBy=vi.fn();
  const element=document.createElement('div');document.body.append(element);const root=createRoot(element);
  cleanup=async()=>{await act(async()=>root.unmount());element.remove();};
  const child=createElement(EnrollmentPlacementWorkbench,{initialBoard:board,canCreateClass:false,now:Date.now()});
  const props={locale:'zh',messages,timeZone:'Asia/Shanghai',children:child};
  await act(async()=>root.render(createElement(NextIntlClientProvider,props)));
  const source=element.querySelector<HTMLElement>(`[data-placement-student="${id(5)}"]`)!;
  const destination=element.querySelector<HTMLElement>(`[data-placement-target="${id(4)}:2"]`)!;
  document.elementFromPoint=()=>destination;
  const send=async(type:string,x:number)=>{const event=new MouseEvent(type,{bubbles:true,button:0,clientX:x,clientY:100});Object.defineProperties(event,{pointerId:{value:1},isPrimary:{value:true}});await act(async()=>source.dispatchEvent(event));};
  await send('pointerdown',20);await send('pointermove',160);
  expect(document.querySelector('[data-placement-drag-preview]')?.textContent).toContain('小林 → 目标班 · 2 号位');
  expect(document.querySelector('[data-placement-drag-preview]')?.textContent).toContain('松开后选择完全调班或临时调班');
  document.elementFromPoint=()=>element.querySelector<HTMLElement>(`[data-placement-classroom="${id(3)}"]`)!;
  await send('pointermove',170);
  expect(document.querySelector('[data-placement-drag-preview]')?.textContent).toContain('小林 → 原班');
  expect(document.querySelector('[data-placement-drag-preview]')?.textContent).toContain('移到具体座位选择落点');
  document.elementFromPoint=()=>destination;
  await send('pointermove',180);await send('pointerup',180);
  expect(document.querySelector('[data-placement-drag-preview]')).toBeNull();
  expect(document.querySelector('[role="dialog"]')?.textContent).toContain('确认调班');
  expect(document.querySelector<HTMLInputElement>('input[value="permanent"]')?.checked).toBe(true);
  expect(document.querySelector<HTMLInputElement>('input[value="temporary"]')).not.toBeNull();
  expect(calls.move).not.toHaveBeenCalled();expect(calls.change).not.toHaveBeenCalled();
  expect(element.querySelector(`[data-placement-classroom="${id(3)}"] [data-placement-student="${id(5)}"]`)).not.toBeNull();
});
