import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const read = (...segments: string[]) => fs.readFileSync(path.join(root, ...segments), "utf8");

describe("teacher microcourse authoring UX", () => {
  it("selects published lectures and inserts the complete release in one transaction", () => {
    const picker = read("src", "features", "teacher-microcourses", "MicrocourseSourcePicker.tsx");
    const actions = read("src", "features", "teacher-microcourses", "actions.ts");
    const courseActions = read("src", "features", "school", "actions", "classes.ts");
    const sharedPicker = read("src", "features", "school", "teaching-operations", "CoursePicker.tsx");
    const catalogPickerMigration = read("supabase", "migrations", "20260827000600_teacher_microcourse_course_catalog_picker.sql");
    const catalogAccessMigration = read("supabase", "migrations", "20260827000700_teacher_microcourse_course_catalog_access.sql");
    const zh = read("messages", "zh.json");
    const en = read("messages", "en.json");

    expect(picker).toContain("aria-pressed={checked}");
    expect(picker).toContain("<CoursePicker");
    expect(picker).toContain('fixedCourseKind="curriculum"');
    expect(picker).toContain('purpose="production"');
    expect(picker).toContain('accessContext="microcourse-source"');
    expect(picker).not.toContain("StagePreview");
    expect(picker).not.toContain("previewDoc");
    expect(picker).toContain("createTeacherCompositionPagesFromLectureAction");
    expect(picker).toContain("source.pageCount");
    expect(picker).not.toContain("for (const revisionId");
    expect(actions).toContain('"create_teacher_microcourse_composition_pages_from_lecture"');
    expect(actions).toContain("listTeacherMicrocourseSourceLectures");
    expect(catalogPickerMigration).toContain("list_teacher_microcourse_source_lectures");
    expect(catalogPickerMigration).toContain("copy_teacher_microcourse_lecture_pages_internal");
    expect(catalogPickerMigration).toContain("from public, anon, authenticated");
    expect(catalogPickerMigration).not.toContain("preview_doc");
    expect(sharedPicker).toContain("searchTeacherMicrocourseSourceCoursesAction");
    expect(courseActions).toContain('"courseware.microcourse.author"');
    expect(catalogAccessMigration).toContain("p_purpose = 'production'");
    expect(catalogAccessMigration).toContain("p_course_kind = 'curriculum'");
    expect(catalogAccessMigration).toContain("can_build_class or course_row.course_kind = 'curriculum'");
    expect(picker).toContain("retrySourceSearch");
    expect(zh).toContain('"insertLecture"');
    expect(en).toContain('"insertLecture"');
    expect(zh).toContain('"sourceCourseLabel"');
    expect(en).toContain('"sourceCourseLabel"');
  });

  it("keeps details compact and autosaves composition pages before navigation", () => {
    const editor = read("src", "features", "teacher-microcourses", "MicrocourseEditor.tsx");
    const workbench = read("src", "features", "teacher-microcourses", "CoursewareCompositionWorkbench.tsx");
    const sharedWorkbench = read("src", "features", "courseware-doc", "CoursewareEditorWorkbench.tsx");
    const adapterSurface = read("src", "features", "courseware-doc", "CoursewareEditorAdapterSurface.tsx");
    const zh = read("messages", "zh.json");
    const en = read("messages", "en.json");

    expect(editor).toContain("const [detailsOpen, setDetailsOpen] = useState(false)");
    expect(editor).toContain("aria-expanded={detailsOpen}");
    expect(workbench).toContain("useImperativeHandle(ref, () => ({ flush, rename })");
    expect(editor).toContain("await persistCurrentPage()");
    expect(workbench).toContain("window.setTimeout(() => void flushRef.current(), 800)");
    expect(workbench).toContain("saveTeacherMicrocoursePageAction");
    expect(editor).toContain("createTeacherCompositionPageAction");
    expect(editor).toContain("CoursewareCompositionWorkbench");
    expect(editor).toContain('data-teacher-microcourse-editor="composition"');
    expect(workbench).toContain('statusTestId="microcourse-autosave-status"');
    expect(editor).toContain("CoursewareWorkbench");
    expect(editor).toContain('mode="microcourse-editor"');
    expect(editor).toContain('layout="viewport"');
    expect(editor).toContain("const [pageTitleDrafts, setPageTitleDrafts]");
    expect(editor).toContain('titleInputLabel={t("renamePage")}');
    expect(editor).toContain("workbenchRef.current?.rename?.(value)");
    expect(workbench).toContain("CoursewareEditorAdapterSurface");
    expect(adapterSurface).toContain("CoursewareStageViewport");
    expect(workbench).toContain("CoursewareInsertionToolbar");
    expect(workbench).toContain("CoursewareEditorToolbarButton");
    expect(workbench).toContain("CoursewareEditorToolbarLabel");
    expect(workbench).toContain("iconOnly onCreated");
    expect(workbench).toContain("iconOnly onSaved");
    expect(workbench).not.toContain('id="composition-insert-title"');
    expect(workbench).not.toContain('<Badge variant="secondary">{t("mode_composition")}</Badge>');
    expect(workbench).toContain("rounded-xl border border-line bg-white shadow-sm");
    expect(editor).toContain("CoursewareWorkbenchPageRail");
    expect(editor).toContain("CoursewareWorkbenchPager");
    expect(editor).not.toMatch(/(?:toolbar|save|inspector).*TARGET_ID/);
    expect(sharedWorkbench).toContain('data-courseware-editor-part="save-controls"');
    expect(adapterSurface).toContain("useCoursewareEditorChrome");
    expect(adapterSurface).not.toContain("createPortal");
    expect(sharedWorkbench).toContain('mode === "formal-editor" ? "enabled" : "disabled"');
    expect(workbench).not.toContain("bg-paper/70");
    expect(zh).toContain('"pageAutosaving"');
    expect(en).toContain('"pageAutosaving"');
  });

  it("saves the selected proposal back to session preparation and keeps catalog review optional", () => {
    const editor = read("src", "features", "teacher-microcourses", "MicrocourseEditor.tsx");
    const sessionWorkspace = read("src", "features", "school", "SessionWorkspaceBody.tsx");
    const classroomActions = read("src", "features", "classroom", "actions.ts");
    const e2e = read("e2e", "teacher-microcourse.spec.ts");
    const zh = read("messages", "zh.json");
    const en = read("messages", "en.json");

    expect(editor).toContain("const saveForSession");
    expect(editor).toContain("selectTeacherMicrocourseVariantAction");
    expect(editor).toContain("/dashboard/sessions/${session.id}?stage=pre");
    expect(editor).toContain('t("catalogSharingTitle")');
    expect(editor).toContain("submitTeacherMicrocourseReviewAction");
    expect(editor).not.toContain("freezeTeacherMicrocourseSourceSessionAction");
    expect(editor).not.toContain("freezeAndTeach");
    expect(sessionWorkspace).toContain("SessionPrepCompleteAction");
    expect(sessionWorkspace).toContain('label: t("enterCandidate")');
    expect(classroomActions).toContain('"freeze_selected_teacher_microcourse_source_session"');
    expect(e2e).not.toContain('name: "冻结并上课"');
    expect(e2e).toContain('name: "保存本节并返回备课"');
    expect(e2e).toContain('name: "进入候课"');
    expect(e2e).toContain('name: "开始上课"');
    expect(zh).toContain('"saveForSessionAndReturn": "保存本节并返回备课"');
    expect(en).toContain('"saveForSessionAndReturn": "Save for session and return"');
  });

  it("loads the selected research version in preparation and copies only for teacher adjustments", () => {
    const prep = read("src", "features", "school", "SessionPrepPanel.tsx");
    const overlayEditor = read("src", "features", "school", "CoursewareOverlayEditor.tsx");
    const coursewareAction = read("src", "features", "school", "actions", "courseware.ts");
    const sessionLearning = read("src", "features", "school", "session-learning.ts");
    const livePage = read("src", "app", "[locale]", "classroom", "[classId]", "session", "[sessionId]", "live", "page.tsx");
    const route = read("src", "app", "[locale]", "dashboard", "sessions", "[sessionId]", "microcourse", "page.tsx");
    const switcher = read("src", "features", "teacher-microcourses", "MicrocourseVariantSwitcher.tsx");
    const variantMigration = read("supabase", "migrations", "20260829000600_teacher_microcourse_class_root.sql");
    const runtimeMigration = read("supabase", "migrations", "20260828000110_teacher_microcourse_variant_runtime.sql");
    const continuityMigration = read("supabase", "migrations", "20260903000200_teacher_microcourse_session_runtime_continuity.sql");
    const readScopeMigration = read("supabase", "migrations", "20260903000300_session_courseware_read_scope.sql");
    const zh = read("messages", "zh.json");
    const en = read("messages", "en.json");

    expect(variantMigration).toContain("if selected_microcourse_id is null then");
    expect(variantMigration).toContain("set selected_teacher_microcourse_id = new_microcourse_id");
    expect(runtimeMigration).toContain("if frozen_at is null and selected_microcourse_id is not null then");
    expect(runtimeMigration).toContain("public.can_read_teacher_microcourse_draft(selected_microcourse_id, uid)");
    expect(prep).toContain("!detail.coursewareFrozenAt && (canViewPrepArchive || canAuthorMicrocourseProposal)");
    expect(prep).toContain("const editorTemplate = frozenEditorState?.template ?? template");
    expect(prep).not.toContain("selectedMicrocourseTemplate");
    expect(prep).toContain("customOnly={!detail.lectureId && sessionDocs.length === 0}");
    expect(prep).not.toContain('t("prepCurrentCoursewareTitle")');
    expect(prep).not.toContain('t("prepResearchCoursewareTitle")');
    expect(coursewareAction).toContain("const template = await getSessionCoursewareTemplate(id)");
    expect(livePage).toContain("const template = await getSessionCoursewareTemplate(sessionId)");
    expect(sessionLearning).toContain('supabase.rpc("get_session_courseware_learning_check_pages"');
    expect(overlayEditor).toContain('from "./session-learning-contract"');
    expect(overlayEditor).not.toContain('from "./session-learning"');
    expect(overlayEditor).toContain("currentPageIds.has(check.sourcePageId)");
    expect(continuityMigration).toContain("resolve_session_courseware_page_snapshot");
    expect(continuityMigration).toContain("public.build_cw_track_snapshot(microcourse_lecture, 'native-16x9')");
    expect(continuityMigration).toContain("get_session_courseware_learning_check_pages");
    expect(continuityMigration).toContain("page_snapshot := public.resolve_session_courseware_page_snapshot(p_session_id)");
    expect(continuityMigration).toContain("learning_checks_configured_at = coalesce(learning_checks_configured_at, now())");
    expect(continuityMigration).toContain("if session_lecture is null and selected_microcourse is not null then");
    expect(continuityMigration).toContain("courseware_value := public.resolve_cw_courseware_overlay(");
    expect(continuityMigration).toContain("get_session_preparation_review_page_docs");
    expect(continuityMigration).toContain("list_session_preparation_review_resolved_assets");
    expect(readScopeMigration).toContain("public.can_read_session_courseware");
    expect(readScopeMigration).toContain("public.is_session_teacher(session.id, p_uid)");
    expect(readScopeMigration).toContain("public.is_classroom_staff_assigned(session.classroom_id, p_uid)");
    expect(readScopeMigration).toContain("public.can_review_session_preparation(session.id, p_uid)");
    expect(readScopeMigration).toContain("public.has_perm(p_uid, 'class.view.all')");
    expect(readScopeMigration).toContain("session.lecture_id is null");
    expect(readScopeMigration).toContain("public.has_perm(p_uid, 'courseware.review')");
    expect(readScopeMigration.match(/not public\.can_read_session_courseware\(p_session_id, uid\)/g)).toHaveLength(4);
    expect(route).toContain("variants.find((variant) => variant.selectedForSession)");
    expect(switcher).toContain("!activeVariant.canEdit && session.canCreate");
    expect(switcher).toContain("forkTeacherMicrocourseVariantAction");
    expect(zh).toContain('"editAsBranch": "复制此版本并调整"');
    expect(en).toContain('"editAsBranch": "Copy and customize"');
  });
});
