"use client";
import { LoaderCircle, Pencil } from "lucide-react";
import { useTranslations } from "next-intl";
import { useState,useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useRouter } from "@/i18n/navigation";
import { updateClassroomAction } from "./actions";
import type { ClassroomDetail } from "./classes";
import { inputClass,selectClass } from "./controls";
export function ClassroomEditor({classroom}:{classroom:ClassroomDetail}){const t=useTranslations("school.classes");const router=useRouter();const [open,setOpen]=useState(false);const [name,setName]=useState(classroom.name);const [grade,setGrade]=useState(classroom.grade?.toString()??"");const [capacity,setCapacity]=useState(classroom.capacity?.toString()??"");const [room,setRoom]=useState(classroom.room);const [failed,setFailed]=useState(false);const [pending,startTransition]=useTransition();const save=()=>startTransition(async()=>{try{await updateClassroomAction(classroom.id,{name,grade:grade?Number(grade):null,capacity:capacity?Number(capacity):null,room});setOpen(false);router.refresh();}catch{setFailed(true);}});return <><Button size="sm" variant="secondary" onClick={()=>setOpen(true)} className="gap-1.5"><Pencil size={15}/>{t("editClass")}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>{t("editClass")}</DialogTitle></DialogHeader><div className="grid gap-3"><label className="grid gap-1 text-xs text-muted">{t("name")}<input value={name} onChange={e=>setName(e.target.value)} className={inputClass}/></label><label className="grid gap-1 text-xs text-muted">{t("gradeLabel")}<select value={grade} onChange={e=>setGrade(e.target.value)} className={selectClass}><option value="">—</option>{Array.from({length:12},(_,i)=>i+1).map(x=><option key={x} value={x}>{t("grade",{grade:x})}</option>)}</select></label><label className="grid gap-1 text-xs text-muted">{t("capacity")}<input type="number" min={1} value={capacity} onChange={e=>setCapacity(e.target.value)} className={inputClass}/></label><label className="grid gap-1 text-xs text-muted">{t("room")}<input value={room} onChange={e=>setRoom(e.target.value)} className={inputClass}/></label></div>{failed&&<p className="text-xs text-rose">{t("actionFailed")}</p>}<DialogFooter><Button size="sm" variant="secondary" onClick={()=>setOpen(false)}>{t("cancel")}</Button><Button size="sm" disabled={pending||!name.trim()} onClick={save}>{pending&&<LoaderCircle size={15} className="animate-spin"/>}{t("save")}</Button></DialogFooter></DialogContent></Dialog></>}
