"use server";
import{getMyPerms}from"@/lib/auth";import type{Json}from"@/lib/database.types";import{createClient}from"@/lib/supabase/server";import{actionError,type ActionResult}from"@/lib/action-result";
export interface ReviewRecord{studentId:string;studentName:string;entryScore:number|null;exitScore:number|null;focus:number|null;participation:number|null;mastery:number|null;comment:string}
export async function getReviewDrawerData(sessionId:string){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user||!(await getMyPerms(user.id)).has("review.write"))throw new Error("FORBIDDEN");const{data:session,error}=await s.from("class_sessions").select("classroom_id,knowledge_summary").eq("id",sessionId).single<{classroom_id:string;knowledge_summary:string}>();if(error)throw new Error(error.message);const[{data:roster,error:re},{data:reviews,error:ve}]=await Promise.all([s.from("enrollments").select("student_id,students(name)").eq("classroom_id",session.classroom_id).eq("status","active").returns<Array<{student_id:string;students:{name:string}|null}>>(),s.from("session_reviews").select("student_id,entry_score,exit_score,focus,participation,mastery,comment").eq("session_id",sessionId).returns<Array<{student_id:string;entry_score:number|null;exit_score:number|null;focus:number|null;participation:number|null;mastery:number|null;comment:string}>>()]);if(re)throw new Error(re.message);if(ve)throw new Error(ve.message);const by=new Map((reviews??[]).map(x=>[x.student_id,x]));return{knowledgeSummary:session.knowledge_summary,records:(roster??[]).map(x=>{const r=by.get(x.student_id);return{studentId:x.student_id,studentName:x.students?.name??"-",entryScore:r?.entry_score??null,exitScore:r?.exit_score??null,focus:r?.focus??null,participation:r?.participation??null,mastery:r?.mastery??null,comment:r?.comment??""}satisfies ReviewRecord})}}
export async function saveSessionReviewsAction(sessionId:string,knowledgeSummary:string,records:ReviewRecord[]):Promise<ActionResult>{
  try{
    const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user||!(await getMyPerms(user.id)).has("review.write"))throw new Error("FORBIDDEN");
    const{error}=await s.rpc("save_session_reviews",{p_session_id:sessionId,p_knowledge_summary:knowledgeSummary,p_records:records as unknown as Json});
    if(error)throw new Error(error.message);
    return{ok:true};
  }catch(error){return actionError(error,["FORBIDDEN","UNAUTHENTICATED"])}
}
