"use client";

import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import{LoaderCircle}from"lucide-react";import{useTranslations}from"next-intl";import{useState,useTransition}from"react";import{Button}from"@/components/ui/button";import{Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle}from"@/components/ui/dialog";import{useAction}from"@/components/action-form";import{useRouter}from"@/i18n/navigation";import{getReviewDrawerData,saveSessionReviewsAction,type ReviewRecord}from"./review-actions";import{fromSelectValue,inputClass,toSelectValue}from"./controls";
export function ReviewDrawer({sessionId}:{sessionId:string}){const t=useTranslations("school.reviews");const router=useRouter();const[open,setOpen]=useState(false);const[summary,setSummary]=useState("");const[rows,setRows]=useState<ReviewRecord[]>([]);const[error,setError]=useState(false);const[loading,startLoad]=useTransition();const load=()=>{setOpen(true);startLoad(async()=>{try{const d=await getReviewDrawerData(sessionId);setSummary(d.knowledgeSummary);setRows(d.records)}catch{setError(true)}})};const set=<K extends keyof ReviewRecord>(i:number,k:K,v:ReviewRecord[K])=>setRows(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r));const{run:saveRun,pending}=useAction((summary:string,rows:ReviewRecord[])=>saveSessionReviewsAction(sessionId,summary,rows),{successMessage:t("saved"),errorMessage:{default:t("failed")},onSuccess:()=>{setOpen(false);router.refresh()}});const save=()=>saveRun(summary,rows);return <><Button size="sm" variant="secondary" disabled={loading} onClick={load}>{t("button")}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{t("title")}</DialogTitle></DialogHeader><Label className="grid gap-1 text-xs font-normal text-muted">{t("summary")}<textarea rows={3} value={summary} onChange={e=>setSummary(e.target.value)} className={inputClass}/></Label><div className="overflow-x-auto"><Table className="w-full min-w-[850px] text-left text-xs"><TableHeader><TableRow>{["student","entry","exit","focus","participation","mastery","comment"].map(k=><TableHead key={k} className="p-2">{t(k)}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r.studentId} className="border-t border-line"><TableCell className="p-2 font-medium">{r.studentName}</TableCell><TableCell className="p-2"><Score value={r.entryScore} set={v=>set(i,"entryScore",v)}/></TableCell><TableCell className="p-2"><Score value={r.exitScore} set={v=>set(i,"exitScore",v)}/></TableCell>{(["focus","participation","mastery"]as const).map(k=><TableCell key={k} className="p-2"><Select value={toSelectValue(String(r[k]??""))} onValueChange={v=>{const raw=fromSelectValue(v);set(i,k,raw?Number(raw):null)}}><SelectTrigger className="h-8"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={toSelectValue("")}>—</SelectItem>{[1,2,3,4,5].map(n=><SelectItem key={n} value={String(n)}>{n}</SelectItem>)}</SelectContent></Select></TableCell>)}<TableCell className="p-2"><Input value={r.comment} onChange={e=>set(i,"comment",e.target.value)} className={inputClass}/></TableCell></TableRow>)}</TableBody></Table></div>{error&&<p className="text-xs text-rose">{t("failed")}</p>}<DialogFooter><Button size="sm" variant="secondary" onClick={()=>setOpen(false)}>{t("cancel")}</Button><Button size="sm" disabled={pending} onClick={save}>{pending&&<LoaderCircle size={15} className="animate-spin"/>}{t("save")}</Button></DialogFooter></DialogContent></Dialog></>}
function Score({value,set}:{value:number|null;set:(v:number|null)=>void}){return <Input type="number" min={0} max={100} step={0.5} value={value??""} onChange={e=>set(e.target.value?Number(e.target.value):null)} className={`${inputClass} w-20`}/>}
