/** 3D 舞台按钮的语义目录。图标表示动作，不以所在教具或参数面板命名。 */
export const SPATIAL_ACTIONS = {
  orbit: { zh: "旋转视角", en: "Orbit camera", icon: "Orbit", group: "camera" },
  pan: { zh: "平移视角", en: "Pan camera", icon: "Hand", group: "camera" },
  fit: { zh: "适合画面", en: "Fit view", icon: "Maximize", group: "camera" },
  cameraSnap: { zh: "视角吸附", en: "Camera snap", icon: "Magnet", group: "camera" },
  axes: { zh: "坐标轴", en: "Axes", icon: "Axes", group: "display" },
  grid: { zh: "参考网格", en: "Reference grid", icon: "Grid2X2", group: "display" },
  select: { zh: "选择对象", en: "Select objects", icon: "MousePointer2", group: "object" },
  selectAll: { zh: "选择范围内全部对象", en: "Select all in scope", icon: "SquareDashedMousePointer", group: "object" },
  deselect: { zh: "取消选中", en: "Deselect", icon: "SquareDashed", group: "object" },
  move: { zh: "移动整个对象", en: "Move object", icon: "Move3D", group: "object" },
  rotate: { zh: "旋转整个对象", en: "Rotate object", icon: "Rotate3D", group: "object" },
  roll: { zh: "沿支撑棱翻滚", en: "Roll over an edge", icon: "Footprints", group: "object" },
  moveSnap: { zh: "移动落点吸附", en: "Position snap", icon: "MoveSnap", group: "object" },
  add: { zh: "添加对象／单位块", en: "Add object or block", icon: "Plus", group: "object" },
  remove: { zh: "删除对象／单位块", en: "Remove object or block", icon: "Trash2", group: "object" },
  group: { zh: "编组", en: "Group", icon: "Group", group: "object" },
  ungroup: { zh: "取消编组", en: "Ungroup", icon: "Ungroup", group: "object" },
  separate: { zh: "分开摆放", en: "Arrange apart", icon: "Separate", group: "object" },
  recenter: { zh: "移回原点", en: "Recenter", icon: "LocateFixed", group: "object" },
  objects: { zh: "对象与尺寸", en: "Objects and dimensions", icon: "Box", group: "object" },
  color: { zh: "整个对象标色", en: "Object color", icon: "PaintBucket", group: "surface" },
  faceColor: { zh: "给面标色", en: "Face color", icon: "Paintbrush", group: "surface" },
  opacity: { zh: "透明度", en: "Opacity", icon: "Opacity", group: "surface" },
  mark: { zh: "面上标注", en: "Face marks", icon: "Stamp", group: "surface" },
  number: { zh: "面上标数", en: "Face numbering", icon: "Hash", group: "surface" },
  labels: { zh: "显示面标签", en: "Face labels", icon: "Tags", group: "display" },
  show: { zh: "显示", en: "Show", icon: "Eye", group: "display" },
  hide: { zh: "隐藏", en: "Hide", icon: "EyeOff", group: "display" },
  layers: { zh: "分层显示", en: "Layers", icon: "Layers3", group: "display" },
  face: { zh: "观察面", en: "Select face", icon: "Square", group: "inspect" },
  edge: { zh: "观察棱", en: "Select edge", icon: "Spline", group: "inspect" },
  vertex: { zh: "观察顶点", en: "Select vertex", icon: "CircleDot", group: "inspect" },
  section: { zh: "截面观察", en: "Cross section", icon: "Section", group: "inspect" },
  sectionOffset: { zh: "移动切平面", en: "Move section plane", icon: "MoveVertical", group: "parameter" },
  measure: { zh: "长度、面积与体积", en: "Measurement", icon: "Ruler", group: "inspect" },
  dimensions: { zh: "设置形状与尺寸", en: "Shape dimensions", icon: "Dimensions", group: "inspect" },
  projection: { zh: "投影视图", en: "Projection", icon: "PanelsTopLeft", group: "inspect" },
  sweep: { zh: "保留旋转扫过的形体", en: "Show swept solid", icon: "Sweep", group: "inspect" },
  faceReveal: { zh: "移面展示", en: "Move faces outward", icon: "FaceReveal", group: "inspect" },
  faceInspect: { zh: "单面观察", en: "Inspect one face", icon: "ScanFace", group: "inspect" },
  xray: { zh: "透视相对面", en: "X-ray opposite face", icon: "ScanEye", group: "inspect" },
  opposite: { zh: "相对面", en: "Opposite faces", icon: "GitCompareArrows", group: "inspect" },
  fold: { zh: "逐面折叠", en: "Fold a face", icon: "FoldHorizontal", group: "fold" },
  foldMode: { zh: "选择展开／折纸方式", en: "Choose folding workspace", icon: "LayoutDashboard", group: "fold" },
  foldAll: { zh: "折合成立体", en: "Fold into a solid", icon: "FoldSolid", group: "fold" },
  unfold: { zh: "依次展开", en: "Unfold in sequence", icon: "UnfoldHorizontal", group: "fold" },
  cut: { zh: "剪棱／拆分", en: "Cut or split", icon: "Scissors", group: "fold" },
  netGallery: { zh: "展开图图集", en: "Net gallery", icon: "NetGallery", group: "fold" },
  paperLayout: { zh: "纸片布局", en: "Paper layout", icon: "LayoutTemplate", group: "fold" },
  validateFold: { zh: "查看折合结果", en: "Inspect fold result", icon: "BadgeCheck", group: "fold" },
  pips: { zh: "骰子点数显隐", en: "Show or hide pips", icon: "Dice5", group: "dice" },
  contact: { zh: "相贴面条件", en: "Contact-face conditions", icon: "Contact", group: "dice" },
  throwDice: { zh: "投掷骰子", en: "Throw dice", icon: "Dices", group: "dice" },
  observe: { zh: "单块观察", en: "Observe one piece", icon: "Focus", group: "soma" },
  assemble: { zh: "自由拼搭", en: "Assemble pieces", icon: "Boxes", group: "soma" },
  pieces: { zh: "选择拼块", en: "Choose pieces", icon: "Shapes", group: "soma" },
  liquid: { zh: "液量与倒水", en: "Liquid and pouring", icon: "Beaker", group: "capacity" },
  amounts: { zh: "显示容积数值", en: "Show amounts", icon: "Gauge", group: "capacity" },
  emptyLiquid: { zh: "倒空容器", en: "Empty vessels", icon: "GlassWater", group: "capacity" },
  settings: { zh: "结构与显示设置", en: "Structure and display", icon: "Settings2", group: "workspace" },
  reset: { zh: "恢复教学起点", en: "Restore starting scene", icon: "RotateCcw", group: "workspace" },
  openScene: { zh: "打开场景", en: "Open scene", icon: "FolderOpen", group: "workspace" },
  saveScene: { zh: "保存场景", en: "Save scene", icon: "Save", group: "workspace" },
  refreshScenes: { zh: "刷新场景列表", en: "Refresh scenes", icon: "RefreshCw", group: "workspace" },
  viewPresets: { zh: "预设视角", en: "View presets", icon: "Camera", group: "camera" },
  undo: { zh: "撤销", en: "Undo", icon: "Undo2", group: "workspace" },
  redo: { zh: "重做", en: "Redo", icon: "Redo2", group: "workspace" },
  prepare: { zh: "准备场景", en: "Prepare scene", icon: "PencilRuler", group: "workspace" },
  compareScenes: { zh: "比较场景变化", en: "Compare scene changes", icon: "GitCompare", group: "workspace" },
  demonstrate: { zh: "演示场景", en: "Demonstrate scene", icon: "Presentation", group: "workspace" },
  record: { zh: "录制步骤", en: "Record steps", icon: "Circle", group: "recording" },
  play: { zh: "播放／继续", en: "Play or resume", icon: "Play", group: "recording" },
  pause: { zh: "暂停", en: "Pause", icon: "Pause", group: "recording" },
  stop: { zh: "停止过程动画", en: "Stop animation", icon: "Square", group: "recording" },
  firstStep: { zh: "初始步骤", en: "First step", icon: "SkipBack", group: "recording" },
  nextStep: { zh: "下一步骤", en: "Next step", icon: "SkipForward", group: "recording" },
  previousStep: { zh: "上一步骤", en: "Previous step", icon: "ChevronLeft", group: "recording" },
  edit: { zh: "编辑步骤", en: "Edit step", icon: "Pencil", group: "recording" },
  increase: { zh: "增加参数", en: "Increase", icon: "Plus", group: "parameter" },
  decrease: { zh: "减少参数", en: "Decrease", icon: "Minus", group: "parameter" },
  positiveTurn: { zh: "沿轴正向旋转", en: "Positive axis turn", icon: "RotateCcw", group: "parameter" },
  negativeTurn: { zh: "沿轴负向旋转", en: "Negative axis turn", icon: "RotateCw", group: "parameter" },
  up: { zh: "上移一步", en: "Step up", icon: "ArrowUp", group: "parameter" },
  down: { zh: "下移一步", en: "Step down", icon: "ArrowDown", group: "parameter" },
  left: { zh: "向左", en: "Left", icon: "ArrowLeft", group: "parameter" },
  right: { zh: "向右", en: "Right", icon: "ArrowRight", group: "parameter" },
  clear: { zh: "清除标记／样式", en: "Clear marks or style", icon: "Eraser", group: "parameter" },
  close: { zh: "关闭面板", en: "Close panel", icon: "X", group: "parameter" },
  confirm: { zh: "确认", en: "Confirm", icon: "Check", group: "parameter" },
  expand: { zh: "展开参数", en: "Expand parameters", icon: "ChevronDown", group: "parameter" },
} as const;

export type SpatialActionId = keyof typeof SPATIAL_ACTIONS;
export type SpatialIconId = (typeof SPATIAL_ACTIONS)[SpatialActionId]["icon"];
