/** 面向维护与视觉核对的教学能力清单；不会被工作台加载，也不创建另一套功能开关。 */
export const SPATIAL_WORKBENCH_INVENTORY = [
  { id: "cube-structures", name: "立方体结构", files: ["spatial-lab/CubeStructuresWorkbench.tsx", "spatial-lab/CubeRecordingPanel.tsx", "spatial-lab/CubeDraftPanel.tsx"],
    features: "添加／挖除单位块；选择、编组／取消编组；整组移动、世界轴转动、翻滚；层显隐；对象／面标色、透明、符号与编号；拆分；指标；步骤录制、编辑、播放与撤销；教学起点。",
    shared: "动作按钮、视角栏、XYZ 步进、颜色／透明度、对象手柄、旋转／翻滚、非模态面板、场景宿主" },
  { id: "projection", name: "投影与多视图", files: ["projection/ProjectionWorkspace.tsx", "spatial-lab/CubeStructuresWorkbench.tsx"],
    features: "继承立方体搭建与展示；正面／侧面／顶面投影开关、连线；投影随同一个 3D 展示帧变化。旧冻结版本保持原动作边界。",
    shared: "直接组合立方体工作台，不维护第二套搭建、移动或按钮" },
  { id: "cube-net", name: "正方体展开／剪棱展开", files: ["spatial-lab/CubeNetFoldWorkspace.tsx", "spatial-lab/CubeNetSurfacePanel.tsx", "net-teaching/NetTeachingWorkspace.tsx"],
    features: "抓纸面折叠；剪棱后逐步展开；11 种展开图和转换过程；移面；面色、透明、字母／符号／数字；归位、撤销、停止动画、折合结果。",
    shared: "折纸拾取与动画；移面语义图标；动作按钮、视角栏、颜色／透明度、标记、非模态面板" },
  { id: "paper-folding", route: "cube-net", name: "自由折纸", files: ["paper-folding/PaperFoldingWorkspace.tsx", "paper-folding/PaperLayoutEditor.tsx"],
    features: "编辑纸片布局；选面和折痕；直接折叠、准确角度；面色、背面显示、面标签；逐步展开、撤销、复原。",
    shared: "折纸拾取；动作按钮、视角栏、颜色、非模态面板；纸片拓扑独立" },
  { id: "solid-nets", route: "cube-net", name: "长方体／三棱柱展开", files: ["solid-nets/SolidNetsWorkspace.tsx"],
    features: "选择形状与尺寸；折叠、整体折合、依次展开；准确角度；面色、背面与面标签；撤销、复原。",
    shared: "折纸拾取；动作按钮、视角栏、颜色与面板；几何终点独立" },
  { id: "dice", name: "骰子", files: ["spatial-lab/DiceTeachingWorkspace.tsx"],
    features: "左右手系、多骰子摆放；整体移动与转动；移面 0.9 个宽度、单面／相对面、动态透视；点数显隐、面色、透明；相贴面条件；受控翻滚与点数轨迹；随机投掷；分项复原与撤销。",
    shared: "动作按钮、视角栏、XYZ 步进、颜色／透明度、对象手柄、旋转／翻滚、非模态面板" },
  { id: "solid-geometry", name: "立体观察、截面与测量", files: ["solid-geometry/SolidGeometryWorkspace.tsx", "solid-sections/SolidSectionControls.tsx", "solid-sections/SolidSectionHandles.tsx", "solid-measurement/MeasurementControls.tsx"],
    features: "添加立体与尺寸设置；平移、转动、长方体翻滚；选面／棱／顶点；对象色和透明；拖动切平面、倾斜、截去一侧、关联截面图；长度、面积、体积、单位网格与分层填充。",
    shared: "动作按钮、视角栏、XYZ 步进、颜色、对象手柄、旋转／翻滚、面板；截面／测量数学独立" },
  { id: "solid-capacity", name: "容积比较", files: ["solid-capacity/SolidCapacityWorkspace.tsx"],
    features: "圆锥与圆柱等底等高／独立尺寸；加满、倒空、定量倒水；容积数值；圆锥朝向；视角、坐标轴与网格。",
    shared: "动作按钮、视角栏、实体画布、相机、面板；液体守恒与倒水动画独立" },
  { id: "soma-cube", name: "索玛立方体", files: ["soma-cube/SomaWorkspace.tsx"],
    features: "单块观察／自由拼搭、选宝、示例与分开摆放；XZ 整块拖动、XYZ／平面手柄；轴环旋转、自由轨迹球、四档自动吸附；翻滚、撤销、复原；网格、坐标轴、标签。",
    shared: "动作按钮、视角栏、XYZ 步进、对象手柄、旋转／翻滚、落点虚线、非模态面板" },
] as const;

/** 本轮确认过的同义异图／异义同图；旧图仅用于核对，不参与实际按钮渲染。 */
export const SPATIAL_ICON_CHANGES = [
  { action: "move", previous: ["Move", "Move3D"], note: "结构、实体、骰子与 Soma 的整体移动统一为三轴箭头。" },
  { action: "faceReveal", previous: ["Move3D"], note: "骰子、剪棱展开共用“面从立方体向外移出”，与移动整个对象分开。" },
  { action: "rotate", previous: ["RotateCw", "Rotate3D"], note: "对象旋转入口统一为三维旋转；正负 90° 参数仍有明确方向。" },
  { action: "opacity", previous: ["Droplets"], note: "半透明圆表示透明度，不再与容积工具的液量图标混用。" },
  { action: "liquid", previous: ["Droplets"], note: "用烧杯表达液量／倒水；液体数学与透明度控件不合并。" },
  { action: "unfold", previous: ["RotateCcw", "FoldHorizontal"], note: "展开是展开纸片，不是复原教学起点。" },
  { action: "section", previous: ["Scissors"], note: "截面观察用平面穿过立体；剪刀留给剪棱／拆分。" },
  { action: "netGallery", previous: ["Shapes"], note: "图集使用六格展开图，与拼块选择、相贴面条件区分。" },
  { action: "pips", previous: ["Eye"], note: "点数面板使用骰子点数；显示／隐藏眼睛仍用于具体显隐动作。" },
  { action: "separate", previous: ["Boxes"], note: "分开摆放不再与自由拼搭模式或编组共用叠块图标。" },
] as const;
