import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const dir = path.join(process.cwd(), "supabase", "migrations");
const rows = [];
for (const name of fs.readdirSync(dir).filter((file) => file.endsWith(".sql") && !file.includes("migration_ledger_snapshot")).sort()) {
  const checksum = crypto.createHash("sha256").update(fs.readFileSync(path.join(dir, name))).digest("hex");
  const version = name.replace(/\.sql$/, "").replaceAll("'", "''");
  rows.push({ version, checksum });
}
const statements = rows.map(({version,checksum}) => `do $$ begin if exists(select 1 from public.schema_migrations where version='${version}' and checksum<>'${checksum}') then raise exception 'MIGRATION_CHECKSUM_MISMATCH: ${version}'; end if; insert into public.schema_migrations(version,checksum) values('${version}','${checksum}') on conflict(version) do nothing; end $$;`).join("\n");
if (process.argv.includes("--write-snapshot")) {
  const snapshotVersion = process.env.MIGRATION_LEDGER_VERSION ?? "20260712009900";
  if (!/^\d{14}$/.test(snapshotVersion)) throw new Error("MIGRATION_LEDGER_VERSION must contain 14 digits");
  const target = path.join(dir, `${snapshotVersion}_p4e_migration_ledger_snapshot.sql`);
  if (fs.existsSync(target)) throw new Error(`Ledger snapshot already exists: ${path.relative(process.cwd(), target)}; choose a new MIGRATION_LEDGER_VERSION`);
  fs.writeFileSync(target, `-- Generated by pnpm migrations:ledger:snapshot; do not edit.\n${statements}\n`, "utf8");
  console.log(`Wrote ${path.relative(process.cwd(), target)} (${rows.length} migrations)`);
} else {
  console.log(statements);
}
