import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const inputPath = path.join(root, "supabase", "seed", "teaching-plans.json");
const outputPath = path.join(root, "supabase", "seed", "courses.seed.sql");

function sqlString(value) {
  if (value === null || value === undefined) return "null";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlNumber(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) throw new Error(`Invalid number: ${value}`);
  return String(number);
}

const raw = await readFile(inputPath, "utf8");
const plans = JSON.parse(raw);
if (!Array.isArray(plans)) throw new Error("teaching-plans.json must contain an array");

const lines = [
  "-- Generated by scripts/seed-courses.mjs. Do not edit by hand.",
  "begin;",
  "",
];

for (const plan of plans) {
  lines.push(
    "insert into public.courses (title, product_code, grade, term, class_type, status)",
    `values (${sqlString(plan.title)}, ${sqlString(plan.productCode)}, ${sqlNumber(plan.grade)}, ${sqlNumber(plan.termIndex)}, ${sqlString(plan.classType)}, 'enabled')`,
    "on conflict (product_code) do update set",
    "  title = excluded.title,",
    "  grade = excluded.grade,",
    "  term = excluded.term,",
    "  class_type = excluded.class_type;",
    "",
  );

  for (const lecture of plan.lectures ?? []) {
    lines.push(
      "insert into public.course_lectures (course_id, no, name)",
      `select id, ${sqlNumber(lecture.no)}, ${sqlString(lecture.name)}`,
      `  from public.courses where product_code = ${sqlString(plan.productCode)}`,
      "on conflict (course_id, no) do update set",
      "  name = excluded.name;",
      "",
    );
  }
}

lines.push("commit;", "");

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, lines.join("\n"), "utf8");
console.log(`Wrote ${path.relative(root, outputPath)} for ${plans.length} courses.`);
