import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const inputPath = path.join(root, "supabase", "seed", "teaching-plans.json");
const outputPath = path.join(root, "supabase", "seed", "courses.seed.sql");
const preFamilyOutputPath = path.join(root, "supabase", "seed", "courses.pre-family.seed.sql");
const familySlug = "xueersi-e-primary-math-cn";

function sqlString(value) {
  if (value === null || value === undefined) return "null";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlNumber(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) throw new Error(`Invalid number: ${value}`);
  return String(number);
}

const raw = await readFile(inputPath, "utf8");
const plans = JSON.parse(raw);
if (!Array.isArray(plans)) throw new Error("teaching-plans.json must contain an array");

function appendLectures(lines, plan) {
  for (const lecture of plan.lectures ?? []) {
    lines.push(
      "insert into public.course_lectures (course_id, no, name)",
      `select id, ${sqlNumber(lecture.no)}, ${sqlString(lecture.name)}`,
      `  from public.courses where product_code = ${sqlString(plan.productCode)}`,
      "on conflict (course_id, no) do update set",
      "  name = excluded.name;",
      "",
    );
  }
}

function createPreFamilySeed() {
  const lines = [
    "-- Generated by scripts/seed-courses.mjs. CI replay seed before P4H-3; do not edit by hand.",
    "begin;",
    "",
  ];
  for (const plan of plans) {
    lines.push(
      "insert into public.courses (title, product_code, grade, term, class_type, status)",
      `values (${sqlString(plan.title)}, ${sqlString(plan.productCode)}, ${sqlNumber(plan.grade)}, ${sqlNumber(plan.termIndex)}, ${sqlString(plan.classType)}, 'enabled')`,
      "on conflict (product_code) do update set",
      "  title = excluded.title,",
      "  grade = excluded.grade,",
      "  term = excluded.term,",
      "  class_type = excluded.class_type;",
      "",
    );
    appendLectures(lines, plan);
  }
  lines.push("commit;", "");
  return lines.join("\n");
}

const lines = [
  "-- Generated by scripts/seed-courses.mjs. Do not edit by hand.",
  "begin;",
  "",
  "insert into public.course_families (slug, title, publisher, stage, subject, edition, purpose, status)",
  `values (${sqlString(familySlug)}, 'E 系列小学数学', '学而思', '小学', '数学', '全国版', 'production', 'enabled')`,
  "on conflict (slug) do update set",
  "  title = excluded.title,",
  "  publisher = excluded.publisher,",
  "  stage = excluded.stage,",
  "  subject = excluded.subject,",
  "  edition = excluded.edition,",
  "  purpose = excluded.purpose,",
  "  status = excluded.status;",
  "",
];

for (const plan of plans) {
  lines.push(
    "insert into public.courses (family_id, title, product_code, grade, term, class_type, status)",
    `values ((select id from public.course_families where slug = ${sqlString(familySlug)}), ${sqlString(plan.title)}, ${sqlString(plan.productCode)}, ${sqlNumber(plan.grade)}, ${sqlNumber(plan.termIndex)}, ${sqlString(plan.classType)}, 'enabled')`,
    "on conflict (product_code) do update set",
    "  family_id = excluded.family_id,",
    "  title = excluded.title,",
    "  grade = excluded.grade,",
    "  term = excluded.term,",
    "  class_type = excluded.class_type;",
    "",
  );

  appendLectures(lines, plan);
}

lines.push("commit;", "");

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, lines.join("\n"), "utf8");
await writeFile(preFamilyOutputPath, createPreFamilySeed(), "utf8");
console.log(`Wrote ${path.relative(root, outputPath)} and ${path.relative(root, preFamilyOutputPath)} for ${plans.length} courses.`);
