const zh = {
  xrayOpening: "正在淡化遮挡", xrayClosing: "正在恢复遮挡",
  xray: "透视观察", xrayActive: "透视中", xrayHint: "点击一个面，原位观察它的相对面；骰子和视角保持不动。", xrayExitHint: "再点高亮面、空白或按 Esc 恢复；拖动仍可旋转。隐藏点数保持隐藏，侧向难读时可正视查看。", xrayClear: "结束本次观察",
  observe: "正视查看", inspectionHint: "正视副本；真实面和主视角保持不变。", moveOneFace: "移开这个面", returnOneFace: "收回这个面", revealOneFace: "显示这个面的点数", hideOneFace: "隐藏这个面的点数", observationHint: "选择一个面查看正视副本；也可垂直于该面直线移开，在舞台中观察它的位置关系。",
  color: "标色", transparent: "透明", surfaceScope: "作用范围", oneFace: "单面", wholeDie: "整颗骰子", colorHint: "选颜色后点击骰子表面标色；也可在下方选面。整颗模式为当前骰子的六个面一起标色。", transparentHint: "先点击表面或下方按钮选面，再调整不透明度；整颗模式同时调整六面。0% 的面仍可选回。", opacity: "不透明度", white: "恢复白色", opaque: "恢复不透明", chooseFace: "请选择一个面", restore: "复原", closeAllFaces: "移面复原（全部骰子）", restoreScene: "整体复原", restoreHint: "移面复原只合拢各面，保留摆放与样式。整体复原保留骰子数量与手性，恢复朝向、白色和点数，并清除轨迹与题设。",
  title: "骰子教学", settings: "工作台与显示", tools: "骰子工具", close: "收起", orbit: "旋转观察", pan: "平移视野", arrange: "摆放骰子", pips: "逐面点数", arrows: "移面箭头", opposite: "相对面", puzzle: "相贴面推理", roll: "受控滚动与留点", throwing: "随机投掷", reset: "回到原点并合拢", fit: "适配视野", undo: "撤销", redo: "重做", bottom: "底面视角",
  views: { angle: "立体视角", front: "正面视角", left: "左侧视角", right: "右侧视角", top: "顶面视角" },
  faces: { "x+": "右面", "x-": "左面", "y+": "上面", "y-": "下面", "z+": "前面", "z-": "后面" },
  die: "骰子", selected: "当前骰子", right: "右手系", left: "左手系", addRight: "加右手骰子", addLeft: "加左手骰子", remove: "移除当前骰子", count: "数量（最多 8 颗）", row: "横向相贴", stack: "上下叠放", corner: "拐角相贴", apart: "分开摆放", turn: "转动当前骰子 90°", move: "移动一格", grid: "网格", axes: "坐标轴", floor: "桌面", memory: "本机教学预演；当前骰子状态暂不保存为账号草稿，也未接入正式课堂同步。",
  dragHint: "拖动骰子在 X–Z 平面摆放；松手吸附到整格。用 Y 按钮上下叠放。拖动空白处仍可旋转视角。", hidden: "已隐藏", visible: "已显示", showAll: "显示全部点数", hideAll: "隐藏全部点数", topOnly: "只显示各骰子的顶面", pipHint: "点击纸面或下面的面按钮，独立显示／隐藏点数。面的位置随当前骰子朝向更新。", pipFaceHint: "点击骰子表面可单独切换点数。", revealPair: "移开这组相对面", closeFaces: "合拢当前骰子", showPair: "揭示这组点数", pairHint: "选择一面，再将它和相对面移开观察。点数继续遵循逐面显隐设置。", pairRule: "三组相对面：1 + 6 = 7，2 + 5 = 7，3 + 4 = 7。",
  each: "每对相贴面的和", total: "所有相贴面的总和", target: "限定的和", generate: "按题设摆面并隐藏答案", reveal: "揭示相贴面", hideAnswer: "隐藏相贴面", puzzleHint: "先相贴摆放，再设置和。生成时会转动骰子满足条件，并隐藏相贴面的点数。", noContacts: "还没有相贴面，请先横向相贴或上下叠放。", impossible: "这个摆法无法满足所设的和，请调整条件或摆放。", searchLimit: "本次搜索未完成，请减少骰子数量或调整条件。", contactClue: "相贴面条件", clearedPuzzle: "摆放或朝向已改变，原题设已清除。",
  rollHint: "每次绕底边翻滚 90°；留下实际底面点数。先分开摆放，为翻起过程留出空间。", trail: "在 X–Z 平面留下点数", clearTrail: "清除点数轨迹", gridReady: "回到网格后滚动", rollBlocked: "请先合拢骰子、放回桌面网格，并在滚动方向留出空间。", placeBlocked: "这个位置已被占用或超出桌面范围。", rollForward: "向 +Z 翻滚", rollBack: "向 −Z 翻滚", rollLeft: "向 −X 翻滚", rollRight: "向 +X 翻滚",
  throwNow: "投掷全部骰子", topAfterThrow: "落定后只显示顶面", throwHint: "真实刚体碰撞决定落点与朝上点数。停稳后可旋转到底部猜其他面，再逐面揭示。", preparing: "正在计算投掷轨迹…", animating: "演示中 · Esc 取消", throwFailed: "投掷模拟暂时不可用，请重试；受控滚动仍可使用。", cocked: "有骰子未平稳落定，请重新投掷。", cancel: "取消演示", fallback: "当前设备未能启动 3D 画布，请启用 WebGL 后重试。",
};
type DiceMessages = { [K in keyof typeof zh]: typeof zh[K] extends string ? string : { [J in keyof typeof zh[K]]: string } };
const en: DiceMessages = {
  xrayOpening: "Fading the obstruction", xrayClosing: "Restoring the obstruction",
  xray: "X-ray observation", xrayActive: "X-ray active", xrayHint: "Click a face to see its opposite in place. Dice and camera stay still.", xrayExitHint: "Click the highlighted face, empty space, or press Esc to restore. Drag to orbit. Hidden pips stay hidden; use Inspect face for an edge-on view.", xrayClear: "End this observation",
  observe: "Inspect face", inspectionHint: "Front-facing copy; the real face and camera stay unchanged.", moveOneFace: "Move this face out", returnOneFace: "Return this face", revealOneFace: "Show this face's pips", hideOneFace: "Hide this face's pips", observationHint: "Select a face for a front-facing copy, or move it straight out along its normal to inspect its spatial relationship in the scene.",
  color: "Color", transparent: "Transparency", surfaceScope: "Apply to", oneFace: "One face", wholeDie: "Whole die", colorHint: "Choose a color, then click a die face or a face button. Whole-die mode colors all six faces of the selected die.", transparentHint: "Select a face in the canvas or below, then adjust opacity. Whole-die mode adjusts all six faces. Faces at 0% remain selectable.", opacity: "Opacity", white: "Restore white", opaque: "Restore opaque", chooseFace: "Select a face", restore: "Restore", closeAllFaces: "Close faces of all dice", restoreScene: "Restore whole scene", restoreHint: "Closing faces preserves arrangements and styles. Whole-scene restore keeps the dice and their handedness, restores orientations, white faces and pips, and clears trails and constraints.",
  title: "Dice teaching", settings: "Workspace & display", tools: "Dice tools", close: "Close", orbit: "Orbit", pan: "Pan view", arrange: "Arrange dice", pips: "Face pips", arrows: "Move-face arrows", opposite: "Opposite faces", puzzle: "Touching-face puzzle", roll: "Controlled roll & trail", throwing: "Random throw", reset: "Return to origin & close faces", fit: "Fit view", undo: "Undo", redo: "Redo", bottom: "Bottom view",
  views: { angle: "3D view", front: "Front view", left: "Left view", right: "Right view", top: "Top view" },
  faces: { "x+": "Right", "x-": "Left", "y+": "Top", "y-": "Bottom", "z+": "Front", "z-": "Back" },
  die: "Die", selected: "Selected die", right: "Right-handed", left: "Left-handed", addRight: "Add right-handed", addLeft: "Add left-handed", remove: "Remove selected die", count: "Count (up to 8)", row: "Touching row", stack: "Stack", corner: "Touching corner", apart: "Separate", turn: "Turn selected die 90°", move: "Move one cell", grid: "Grid", axes: "Axes", floor: "Table", memory: "Local teaching preview. Dice state is not yet saved to account drafts or synchronized with a live classroom.",
  dragHint: "Drag a die along X–Z; release to snap to the grid. Use Y buttons to stack. Drag empty space to orbit.", hidden: "Hidden", visible: "Visible", showAll: "Show all pips", hideAll: "Hide all pips", topOnly: "Show top faces only", pipHint: "Click a face or a face button to show/hide its pips independently. Face positions follow the selected die's orientation.", pipFaceHint: "Click a die face to toggle its pips.", revealPair: "Move this opposite pair apart", closeFaces: "Close selected die", showPair: "Reveal this pair", pairHint: "Select a face, then move it and its opposite apart. Per-face pip visibility is preserved.", pairRule: "Opposite pairs: 1 + 6 = 7, 2 + 5 = 7, 3 + 4 = 7.",
  each: "Sum for each touching pair", total: "Total of all touching faces", target: "Required sum", generate: "Orient to constraint & hide answers", reveal: "Reveal touching faces", hideAnswer: "Hide touching faces", puzzleHint: "Arrange touching dice, then set a sum. Generation rotates dice to satisfy it and hides the touching pips.", noContacts: "No touching faces yet. Start with a touching row or stack.", impossible: "This arrangement cannot satisfy that sum. Adjust the constraint or layout.", searchLimit: "Search limit reached. Try fewer dice or adjust the constraint.", contactClue: "Touching-face constraint", clearedPuzzle: "The arrangement or orientation changed; the previous constraint was cleared.",
  rollHint: "Roll 90° around a bottom edge and leave the actual bottom-face pips. Separate dice first to leave room for the roll.", trail: "Leave pips on the X–Z plane", clearTrail: "Clear pip trail", gridReady: "Return to grid for rolling", rollBlocked: "Close the faces, place the die on the table grid, and leave space in the rolling direction.", placeBlocked: "That position is occupied or outside the table.", rollForward: "Roll toward +Z", rollBack: "Roll toward −Z", rollLeft: "Roll toward −X", rollRight: "Roll toward +X",
  throwNow: "Throw all dice", topAfterThrow: "Show only top faces after landing", throwHint: "Rigid-body collisions determine the landing and top faces. Orbit underneath after settling to guess other faces, then reveal them individually.", preparing: "Calculating throw…", animating: "Playing · Esc to cancel", throwFailed: "Throw simulation is unavailable. Retry, or use controlled rolling.", cocked: "Some dice did not settle flat. Throw again.", cancel: "Cancel animation", fallback: "The 3D canvas could not start. Enable WebGL and retry.",
};
export function diceTeachingMessages(locale: string): DiceMessages { return locale === "en" ? en : zh; }
